package eldritch.surge.enchantment.mechanics;

import eldritch.surge.enchantment.ench.*;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

public final class ModEnchantmentDefinitions {
    public static final List<ModEnchantmentDefinition> ALL = List.of(
            ArmoredEnchantment.DEFINITION,
            EngineEnchantment.DEFINITION,
            BlessingOfTheNightEnchantment.DEFINITION,
            EndBlessingEnchantment.DEFINITION,
            HellBlessingEnchantment.DEFINITION,
            SunBlessingEnchantment.DEFINITION,
            VisionBlessingEnchantment.DEFINITION,
            HealthUpgradeEnchantment.DEFINITION,
            GodProtectionEnchantment.DEFINITION,
            RabbitFootEnchantment.DEFINITION,
            SeekerBlessingEnchantment.DEFINITION,
            SpiritCastEnchantment.DEFINITION,
            SwiftnessEnchantment.DEFINITION,
            HeartOfDepthEnchantment.DEFINITION,
            HeartOfNetherEnchantment.DEFINITION,
            HeartOfTheSeaEnchantment.DEFINITION,
            HeartOfTheSkyEnchantment.DEFINITION,
            EndAdaptabilityEnchantment.DEFINITION,
            HealingAuraEnchantment.DEFINITION,
            HickerEnchantment.DEFINITION,
            IceSpeedEnchantment.DEFINITION,
            SnowshoeingEnchantment.DEFINITION,
            SoftFallingEnchantment.DEFINITION,
            SoilFallingEnchantment.DEFINITION,
            CombustionProtectionEnchantment.DEFINITION,
            DwarfFlakesEnchantment.DEFINITION,
            DwarfForgedEnchantment.DEFINITION,
            EndFlakesEnchantment.DEFINITION,
            EndForgedEnchantment.DEFINITION,
            HellFlakesEnchantment.DEFINITION,
            NetherForgedEnchantment.DEFINITION,
            SeaFlakesEnchantment.DEFINITION,
            VillagerForgedEnchantment.DEFINITION,
            WeaponProtectionEnchantment.DEFINITION,
            BackslashEnchantment.DEFINITION,
            BaneOfEndEnchantment.DEFINITION,
            BladeOfApocalypseEnchantment.DEFINITION,
            ButcherEnchantment.DEFINITION,
            CatapultEnchantment.DEFINITION,
            ClearmindEnchantment.DEFINITION,
            CreepingThreatEnchantment.DEFINITION,
            CurseOfPerishEnchantment.DEFINITION,
            CurseOfSpiderEnchantment.DEFINITION,
            DashEnchantment.DEFINITION,
            DualSweepingEnchantment.DEFINITION,
            ExorcistEnchantment.DEFINITION,
            ExperiencedEnchantment.DEFINITION,
            FloggingEnchantment.DEFINITION,
            FreezeAspectEnchantment.DEFINITION,
            GreamReaperEnchantment.DEFINITION,
            HerbicideEnchantment.DEFINITION,
            InkingEnchantment.DEFINITION,
            KatanaEnchantment.DEFINITION,
            LaunchEnchantment.DEFINITION,
            LeechingAspectEnchantment.DEFINITION,
            LungeEnchantment.DEFINITION,
            MidasTouchEnchantment.DEFINITION,
            NeptunesWillEnchantment.DEFINITION,
            PaybackEnchantment.DEFINITION,
            QuickHitEnchantment.DEFINITION,
            SeaBreezeEnchantment.DEFINITION,
            SmootherEnchantment.DEFINITION,
            StarFateEnchantment.DEFINITION,
            SuperweightEnchantment.DEFINITION,
            TriumphEnchantment.DEFINITION,
            UndeadSlayerEnchantment.DEFINITION,
            VoidSweepEnchantment.DEFINITION,
            WitchHunterEnchantment.DEFINITION,
            WrathOfTheAbyssEnchantment.DEFINITION,
            CurseOfTargetEnchantment.DEFINITION,
            ElasticityEnchantment.DEFINITION,
            NinelevenEnchantment.DEFINITION,
            PiercingEnchantment.DEFINITION,
            PopEnchantment.DEFINITION,
            ReplenishEnchantment.DEFINITION,
            SniperEnchantment.DEFINITION,
            TheftEnchantment.DEFINITION,
            DiggerEnchantment.DEFINITION,
            ExcavatorEnchantment.DEFINITION,
            PruningEnchantment.DEFINITION,
            SickenedOfHellEnchantment.DEFINITION,
            SmeltingEnchantment.DEFINITION,
            SmithcraftsEnchantment.DEFINITION,
            RefillEnchantment.DEFINITION,
            SiphonEnchantment.DEFINITION,
            VacuumEnchantment.DEFINITION,
            CocktailSpellEnchantment.DEFINITION,
            RagnarokEnchantment.DEFINITION,
            RedMoonEnchantment.DEFINITION,
            StormSpellEnchantment.DEFINITION,
            TrenchSpellEnchantment.DEFINITION,
            CurseOfFragilityEnchantment.DEFINITION,
            CurseOfTheForestEnchantment.DEFINITION,
            DeathbreakEnchantment.DEFINITION,
            EnduringEnchantment.DEFINITION,
            SoulbondEnchantment.DEFINITION,
            HeavyImpactEnchantment.DEFINITION,
            GravityWellEnchantment.DEFINITION,
            SeismicWaveEnchantment.DEFINITION,
            CometSlamEnchantment.DEFINITION,
            PhalanxStanceEnchantment.DEFINITION,
            ImpalerReachEnchantment.DEFINITION,
            VanguardChargeEnchantment.DEFINITION,
            HeartseekerEnchantment.DEFINITION,
            WeldingEnchantment.DEFINITION
    );

    public static final Map<String, ModEnchantmentDefinition> BY_ID = ALL.stream()
            .collect(Collectors.toUnmodifiableMap(ModEnchantmentDefinition::id, Function.identity()));

    private ModEnchantmentDefinitions() {
    }
}


